TPL_ITEM.IT1 = ItemTpl("TreasureChest")
    .name("物品1")
    .bindAbility(TPL_ABILITY.AB1)
    .icon("AB1")
    .levelMax(9)
    .gold(10)
    .silver(5)
    .copper(3)
    .onGet(function(evtData)

end)