TPL_ITEM.IT1 = ItemTpl("TreasureChest")
    .name("物品1")
    .bindAbilityTpl(TPL_ABILITY.AB1)
    .icon("AB4")
    .levelMax(9)
    .worth({ gold = 10, silver = 5, copper = 3 })
    .charges(2)
    .onGet(function(evtData)

end)