TPL_ITEM.IT2 = ItemTpl("TreasureChest")
    .name("物品2")
    .bindAbility(TPL_ABILITY.King)
    .icon("AB1")
    .levelMax(9)
    .gold(10)
    .silver(5)
    .copper(3)
    .onGet(function(evtData)

end)