_assets_model(":Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl", "FireBallMissile") --大法火球
_assets_model(":Abilities\\Weapons\\BloodElfMissile\\BloodElfMissile.mdl", "BloodElfMissile") --血法火球
_assets_model(":Abilities\\Weapons\\Mortar\\MortarMissile.mdl", "MortarMissile") --迫击炮小队
_assets_model(":Abilities\\Weapons\\GryphonRiderMissile\\GryphonRiderMissile.mdl", "GryphonRiderMissile") --狮鹫
_assets_model(":Abilities\\Weapons\\SteamTank\\SteamTankImpact.mdl", "SteamTankImpact") --蒸汽机车
_assets_model(":Abilities\\Weapons\\BloodElfSpellThiefMISSILE\\BloodElfSpellThiefMISSILE.mdl", "BloodElfSpellThiefMissile") --蒸汽机车
_assets_model(":Abilities\\Weapons\\PriestMissile\\PriestMissile.mdl", "PriestMissile") --牧师
_assets_model(":Abilities\\Weapons\\SorceressMissile\\SorceressMissile.mdl", "SorceressMissile") --女巫
_assets_model(":Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl", "BloodElfMissile") --魔法破坏者
_assets_model(":Abilities\\Weapons\\DragonHawkMissile\\DragonHawkMissile.mdl", "DragonHawkMissile") --龙鹰
_assets_model(":Abilities\\Weapons\\PhoenixMissile\\Phoenix_Missile.mdl", "PhoenixMissile") --凤凰火焰
_assets_model(":Abilities\\Weapons\\GuardTowerMissile\\GuardTowerMissile.mdl", "GuardTowerMissile") --箭塔
_assets_model(":Abilities\\Weapons\\CannonTowerMissile\\CannonTowerMissile.mdl", "CannonTowerMissile") --炮塔
_assets_model(":Abilities\\Spells\\Undead\\OrbOfDeath\\OrbOfDeathMissile.mdl", "OrbOfDeathMissile") --神秘之塔
_assets_model(":Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl", "FarseerMissile") --先知电球
_assets_model(":Abilities\\Weapons\\ShadowHunterMissile\\ShadowHunterMissile.mdl", "ShadowHunterMissile") --暗影猎手
_assets_model(":abilities\\weapons\\huntermissile\\huntermissile.mdl", "hunterMissile") --巨魔猎头
_assets_model(":abilities\\weapons\\DemolisherMissile\\DemolisherMissile.mdl", "DemolisherMissile") --粉碎者
_assets_model(":abilities\\weapons\\WyvernSpear\\WyvernSpearMissile.mdl", "WyvernSpearMissile") --风骑士
_assets_model(":Abilities\\Weapons\\BatTrollMissile\\BatTrollMissile.mdl", "BatTrollMissile") --蝙蝠骑士
_assets_model(":Abilities\\Weapons\\WitchDoctorMissile\\WitchDoctorMissile.mdl", "WitchDoctorMissile") --巨魔巫医
_assets_model(":Abilities\\Weapons\\KeeperGroveMissile\\KeeperGroveMissile.mdl", "KeeperGroveMissile") --老鹿
_assets_model(":Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl", "MoonPriestessMissile") --白虎箭
_assets_model(":Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile.mdl", "DemonHunterMissile") --恶魔猎手混沌
_assets_model(":Abilities\\Weapons\\Arrow\\ArrowMissile.mdl", "ArrowMissile") --箭
_assets_model(":Abilities\\Weapons\\SentinelMissile\\SentinelMissile.mdl", "SentinelMissile") --猎手刀
_assets_model(":Abilities\\Weapons\\Dryadmissile\\Dryadmissile.mdl", "DryadMissile") --树妖
_assets_model(":Abilities\\Weapons\\GlaiveMissile\\GlaiveMissile.mdl", "GlaiveMissile") --投刃车
_assets_model(":Abilities\\Weapons\\ChimaeraAcidMissile\\ChimaeraAcidMissile.mdl", "ChimaeraAcidMissile") --奇美拉
_assets_model(":Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl", "DruidoftheTalonMissile") --德鲁伊
_assets_model(":Abilities\\Weapons\\FaerieDragonMissile\\FaerieDragonMissile.mdl", "FaerieDragonMissile") --精灵龙
_assets_model(":Abilities\\Weapons\\AncientProtectorMissile\\AncientProtectorMissile.mdl", "AncientProtectorMissile") --远古守卫树
_assets_model(":Abilities\\Weapons\\SpiritOfVengeanceMissile\\SpiritOfVengeanceMissile.mdl", "SpiritOfVengeanceMissile") --复仇天神
_assets_model(":Abilities\\Weapons\\VengeanceMissile\\VengeanceMissile.mdl", "VengeanceMissile") --复仇之魂
_assets_model(":Abilities\\Weapons\\LichMissile\\LichMissile.mdl", "LichMissile") --巫妖
_assets_model(":Abilities\\Weapons\\ZigguratMissile\\ZigguratMissile.mdl", "ZigguratMissile") --幽魂之塔
_assets_model(":Abilities\\Weapons\\ZigguratFrostMissile\\ZigguratFrostMissile.mdl", "ZigguratFrostMissile") --蛛网之塔
_assets_model(":Abilities\\Weapons\\MeatwagonMissile\\MeatwagonMissile.mdl", "MeatWagonMissile") --绞肉车
_assets_model(":Abilities\\Weapons\\CryptFiendMissile\\CryptFiendMissile.mdl", "CryptFiendMissile") --不死蜘蛛
_assets_model(":Abilities\\Weapons\\GargoyleMissile\\GargoyleMissile.mdl", "GargoyleMissile") --石像鬼
_assets_model(":Abilities\\Weapons\\BansheeMissile\\BansheeMissile.mdl", "BansheeMissile") --女妖
_assets_model(":Abilities\\Weapons\\NecromancerMissile\\NecromancerMissile.mdl", "NecromancerMissile") --不死族巫师
_assets_model(":Abilities\\Weapons\\FrostWyrmMissile\\FrostWyrmMissile.mdl", "FrostWyrmMissile") --冰霜巨龙
_assets_model(":Abilities\\Weapons\\SkeletalMageMissile\\SkeletalMageMissile.mdl", "SkeletalMageMissile") --骷髅魔法师
_assets_model(":Abilities\\Weapons\\NagaArrowMissile\\NagaArrowMissile.mdl", "NagaArrowMissile") --美杜莎
_assets_model(":Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl", "WingedSerpentMissile") --娜迦飞蛇
_assets_model(":Abilities\\Weapons\\snapMissile\\snapMissile.mdl", "SnapMissile") --飞龙
_assets_model(":Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl", "WaterElementalMissile") --水元素
_assets_model(":Abilities\\Weapons\\SeaElementalMissile\\SeaElementalMissile.mdl", "SeaElementalMissile") --海元素
_assets_model(":Abilities\\Weapons\\RedDragonBreath\\RedDragonMissile.mdl", "RedDragonMissile") --红龙
_assets_model(":Abilities\\Weapons\\GreenDragonMissile\\GreenDragonMissile.mdl", "GreenDragonMissile") --绿龙
_assets_model(":Abilities\\Weapons\\AvengerMissile\\AvengerMissile.mdl", "AvengerMissile") --耐瑟毒龙
_assets_model(":Abilities\\Weapons\\LordofFlameMissile\\LordofFlameMissile.mdl", "LordofFlameMissile") --火焰巨魔
_assets_model(":Abilities\\Weapons\\BrewmasterMissile\\BrewmasterMissile.mdl", "BrewmasterMissile") --酒仙炼金酒瓶

_assets_model(":units\\human\\HeroPaladin\\HeroPaladin", "HeroPaladin") --圣骑士
_assets_model(":units\\human\\HeroArchMage\\HeroArchMage", "HeroArchMage") --大魔法师
_assets_model(":units\\ther\\HeroArchMageGhost\\HeroArchMageGhost", "HeroArchMageGhost") --大魔法师(魂)
_assets_model(":units\\human\\HeroMountainKing\\HeroMountainKing", "HeroMountainKing")--山丘之王
_assets_model(":units\\human\\HeroBloodElf\\HeroBloodElf", "HeroBloodElf") --血魔法师
_assets_model(":units\\human\\Arthas\\Arthas", "Arthas") --阿尔塞斯
_assets_model(":units\\human\\ArthaswithSword\\ArthaswithSword", "ArthaswithSword") --阿尔塞斯(剑)
_assets_model(":units\\other\\Proudmoore\\Proudmoore", "Proudmoore", { Art = "unit\\hero\\Captain" })--海军上将普洛德摩尔
_assets_model(":units\\human\\Jaina\\Jaina", "Jaina") --吉安娜
_assets_model(":units\\creeps\\LordGarithos\\LordGarithos", "LordGarithos") --加理瑟斯
_assets_model(":units\\creeps\\SylvanusWindrunner\\SylvanusWindrunner", "SylvanusWindrunner") --追风之西尔瓦娜斯
_assets_model(":units\\orc\\HeroBladeMaster\\HeroBladeMaster", "HeroBladeMaster") --剑圣绿
_assets_model(":units\\demon\\HeroChaosBladeMaster\\HeroChaosBladeMaster", "HeroChaosBladeMaster") --剑圣红
_assets_model(":units\\orc\\Hellscream\\Hellscream", "Hellscream") --地狱咆哮
_assets_model(":units\\demon\\ChaosHellscream\\ChaosHellscream", "ChaosHellscream") --地狱咆哮红
_assets_model(":units\\orc\\HeroFarSeer\\HeroFarSeer", "HeroFarSeer") --先知
_assets_model(":units\\orc\\Thrall\\Thrall", "Thrall") --萨尔
_assets_model(":units\\orc\\HeroTaurenChieftain\\HeroTaurenChieftain", "HeroTaurenChieftain") --牛头人酋长
_assets_model(":units\\orc\\HeroShadowHunter\\HeroShadowHunter", "HeroShadowHunter") --暗影猎手
_assets_model(":Units\\Other\\Rexxar\\Rexxar", "Rexxar") --兽王
_assets_model(":units\\undead\\HeroDeathKnight\\HeroDeathKnight", "HeroDeathKnight") --死骑
_assets_model(":units\\undead\\HeroLich\\HeroLich", "HeroLich") --巫妖
_assets_model(":units\\undead\\HeroDreadLord\\HeroDreadLord", "HeroDreadLord") --恐惧魔王
_assets_model(":units\\undead\\HeroCryptLord\\HeroCryptLord", "HeroCryptLord") --地穴领主
_assets_model(":units\\undead\\Kelthuzad\\Kelthuzad", "Kelthuzad") --克尔苏加德
_assets_model(":units\\undead\\KelThuzadGhost\\KelThuzadGhost", "KelThuzadGhost") --克尔苏加德 (幽灵)
_assets_model(":units\\demon\\HeroPitLord\\HeroPitLord", "HeroPitLord") --深渊魔王
_assets_model(":units\\demon\\Warlock\\Warlock", "Warlock") --阿克蒙德
_assets_model(":units\\demon\\Kiljaeden\\Kiljaeden", "Kiljaeden") --基尔加丹
_assets_model(":Units\\Creeps\\BansheeRanger\\BansheeRanger", "BansheeRanger") --黑暗游侠
_assets_model(":Units\\Creeps\\HeroFlameLord\\HeroFlameLord", "HeroFlameLord") --火焰巨魔
_assets_model(":Units\\Creeps\\HeroGoblinAlchemist\\HeroGoblinAlchemist", "HeroGoblinAlchemist") --炼金术士
_assets_model(":Units\\Creeps\\HeroTinker\\HeroTinker", "HeroTinker") --修补匠
_assets_model(":units\\naga\\HeroNagaSeawitch\\HeroNagaSeawitch", "HeroNagaSeawitch") --美杜莎
_assets_model(":units\\other\\DranaiAkama\\DranaiAkama", "DranaiAkama") --阿卡玛
_assets_model(":Units\\Creeps\\PandarenBrewmaster\\PandarenBrewmaster", "PandarenBrewmaster") --熊猫酒仙
_assets_model(":Units\\Creeps\\EarthPandarenBrewmaster\\EarthPandarenBrewmaster", "EarthPandarenBrewmaster") --熊猫大地
_assets_model(":Units\\Creeps\\StormPandarenBrewmaster\\StormPandarenBrewmaster", "StormPandarenBrewmaster") --熊猫雷暴
_assets_model(":Units\\Creeps\\FirePandarenBrewmaster\\FirePandarenBrewmaster", "FirePandarenBrewmaster") --熊猫烈焰