TPL_UNIT.Footman = UnitTpl("Footman")
    .superposition("attack", 1)
    .reborn(3)
    .hp(300)
    .mp(100).mpRegen(5)
    .move(0)

TPL_UNIT.MortarTeam = UnitTpl("MortarTeam")
    .superposition("attack", 1)
    .hp(100)
    .attack(3).attackRange(300).attackSpaceBase(0.3)
    .move(100)
    .missilePush(Missile("MortarMissile").height(500).hover(100).speed(300))

TPL_UNIT.Rifleman = UnitTpl("Rifleman")
    .superposition("attack", 1)
    .hp(100)
    .attack(3).attackRange(300).attackSpaceBase(0.3)
    .move(100)
    .missilePush(Missile("FireBallMissile").height(0).hover(100).speed(350))

TPL_UNIT.BloodElfDragonHawk = UnitTpl("BloodElfDragonHawk")
    .superposition("attack", 1)
    .hp(100)
    .attack(3).attackRange(300).attackSpaceBase(0.3)
    .move(100)
    .missilePush(Missile("DragonHawkMissile").height(0).hover(50).speed(200))

TPL_UNIT.WyvernRider = UnitTpl("WyvernRider")
    .superposition("attack", 1)
    .hp(100)
    .attack(3).attackRange(300).attackSpaceBase(0.3)
    .flyHeight(200)
    .move(100)
    .missilePush(Missile("GryphonRiderMissile").height(0).hover(50).speed(400))

TPL_UNIT.ChaosWarlockGreen = UnitTpl("ChaosWarlockGreen")
    .superposition("attack", 1)
    .hp(100)
    .attack(3).attackRange(300).attackSpaceBase(0.3)
    .move(100)
    .lightningPush(Lightning(LIGHTNING_TYPE.thunderRed))