--- 火焰巨魔
TPL_UNIT.HeroFlameLord = UnitTpl("HeroFlameLord")
    .primary(UNIT_PRIMARY.int)
    .missilePush(Missile("SorceressMissile").homing(true).height(220).speed(700).reflex(3))
    .itemSlot({ TPL_ITEM.IT1, TPL_ITEM.IT2 })
    .abilitySlot({ TPL_ABILITY.AB1, TPL_ABILITY.AB2, TPL_ABILITY.AB3, TPL_ABILITY.AB4, TPL_ABILITY.AB5, TPL_ABILITY.King })
    .hp(5000)
    .hpRegen(0)
    .mp(100)
    .mpRegen(10)
    .primary(UNIT_PRIMARY.agi)
    .level(1)
    .reborn(2)
    .move(522)
    .moveType(UNIT_MOVE_TYPE.amphibious)
    .attackSpaceBase(1).attack(130).attackRange(1000)
    .enchantWeapon("fire", "+=1")
    .crit(10)
    .odds("crit", 10)
    .punish(200)
    .attributes({ { "defend", 3, 3 } })
    .attackPoint(0.5)
    .weaponSoundMode(2)
    .weaponSound("metal_bash_heavy")
    .weaponLength(100)
    .weaponHeight(80)