--- 火焰巨魔
TPL_UNIT.HeroFlameLord = UnitTpl("HeroFlameLord")
    .primary(UNIT_PRIMARY.int)
    .superposition("attack", 1)
    .missilePush(Missile("FaerieDragonMissile").homing(true).height(400).speed(500).reflex(2).shake("rand").shakeOffset(1000))
    .itemSlot({ TPL_ITEM.IT1 })
    .abilitySlot({ TPL_ABILITY.AB1, TPL_ABILITY.AB2, TPL_ABILITY.AB3, TPL_ABILITY.AB4 })
    .hp(1000)
    .hpRegen(25)
    .mp(100)
    .mpRegen(10)
    .primary(UNIT_PRIMARY.agi)
    .level(1)
    .reborn(0.5)
    .move(522)
    .attackSpaceBase(0.1).attack(10).attackRange(800).attackSpeed(100)
    .crit(10)
    .odds("crit", 10)
    .punish(2000)