--- 蝎子
TPL_UNIT.HeroPitLord = UnitTpl("HeroPitLord")
--.superposition("attack", 0)
    .itemSlot({ TPL_ITEM.IT1, TPL_ITEM.IT2 })
    .hp(5000)
    .hpRegen(0)
    .mp(80)
    .mpRegen(10)
--.abilitySlot({ TPL_ABILITY.Rebound, TPL_ABILITY.AB4, TPL_ABILITY.King })
    .primary(UNIT_PRIMARY.int)
    .reborn(2)
    .move(0)
    .attack(50)
    .attackSpaceBase(1)
    .attackRange(1000)
    .lightningPush(Lightning(LIGHTNING_TYPE.suckBlue))
    .enchantAppend("grass", "+=1")
    .punish(1)
    .material(UNIT_MATERIAL.metal)